<a href="https://colab.research.google.com/github/sarthakkar99/BDA594-Sarthak_Kar/blob/main/House_Price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving train.csv to train (2).csv

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("train.csv")

In [ ]:
df.head()

,id,squareMeters,numberOfRooms,hasYard,hasPool,floors,cityCode,cityPartRange,numPrevOwners,made,isNewBuilt,hasStormProtector,basement,attic,garage,hasStorageRoom,hasGuestRoom,price
0,0,34291,24,1,0,47,35693,2,1,2000,0,1,8,5196,369,0,3,3436795.2
1,1,95145,60,0,1,60,34773,1,4,2000,0,1,729,4496,277,0,6,9519958.0
2,2,92661,45,1,1,62,45457,4,8,2020,1,1,7473,8953,245,1,9,9276448.1
3,3,97184,99,0,0,59,15113,1,1,2000,0,1,6424,8522,256,1,9,9725732.2
4,4,61752,100,0,0,57,64245,8,4,2018,1,0,7151,2786,863,0,7,6181908.8

In [ ]:
len(df)

22730

In [ ]:
df.columns

Index(['id', 'squareMeters', 'numberOfRooms', 'hasYard', 'hasPool', 'floors',
       'cityCode', 'cityPartRange', 'numPrevOwners', 'made', 'isNewBuilt',
       'hasStormProtector', 'basement', 'attic', 'garage', 'hasStorageRoom',
       'hasGuestRoom', 'price'],
      dtype='object')

In [ ]:
dict1={}
dict2={}
select_columns=[]
str_columns=[]
for column in df.columns:
  dict1[column]=df[column].nunique()
  dict2[column]=df[column].dtypes
  if df[column].dtypes != 'O':
    select_columns.append(column)
  else:
    str_columns.append(column)
print(dict1)
print(dict2)
select_columns

{'id': 22730, 'squareMeters': 7319, 'numberOfRooms': 100, 'hasYard': 2, 'hasPool': 2, 'floors': 101, 'cityCode': 7810, 'cityPartRange': 10, 'numPrevOwners': 10, 'made': 33, 'isNewBuilt': 2, 'hasStormProtector': 2, 'basement': 4903, 'attic': 5167, 'garage': 896, 'hasStorageRoom': 2, 'hasGuestRoom': 11, 'price': 7421}
{'id': dtype('int64'), 'squareMeters': dtype('int64'), 'numberOfRooms': dtype('int64'), 'hasYard': dtype('int64'), 'hasPool': dtype('int64'), 'floors': dtype('int64'), 'cityCode': dtype('int64'), 'cityPartRange': dtype('int64'), 'numPrevOwners': dtype('int64'), 'made': dtype('int64'), 'isNewBuilt': dtype('int64'), 'hasStormProtector': dtype('int64'), 'basement': dtype('int64'), 'attic': dtype('int64'), 'garage': dtype('int64'), 'hasStorageRoom': dtype('int64'), 'hasGuestRoom': dtype('int64'), 'price': dtype('float64')}

['id',
 'squareMeters',
 'numberOfRooms',
 'hasYard',
 'hasPool',
 'floors',
 'cityCode',
 'cityPartRange',
 'numPrevOwners',
 'made',
 'isNewBuilt',
 'hasStormProtector',
 'basement',
 'attic',
 'garage',
 'hasStorageRoom',
 'hasGuestRoom',
 'price']

In [ ]:
str_columns

[]

In [ ]:
import pandas as pd

# Assuming str_columns is a list of column names with string values
df1 = df.copy()  # Create a copy of the original DataFrame

for column in str_columns:
    unique_values = df1[column].unique()  # Get unique values in the column
    mapping = {value: index for index, value in enumerate(unique_values)}  # Create a mapping from string to integer
    df1[column] = df1[column].map(mapping)  # Use map to replace string values with integers

df1

,id,squareMeters,numberOfRooms,hasYard,hasPool,floors,cityCode,cityPartRange,numPrevOwners,made,isNewBuilt,hasStormProtector,basement,attic,garage,hasStorageRoom,hasGuestRoom,price
0,0,34291,24,1,0,47,35693,2,1,2000,0,1,8,5196,369,0,3,3436795.2
1,1,95145,60,0,1,60,34773,1,4,2000,0,1,729,4496,277,0,6,9519958.0
2,2,92661,45,1,1,62,45457,4,8,2020,1,1,7473,8953,245,1,9,9276448.1
3,3,97184,99,0,0,59,15113,1,1,2000,0,1,6424,8522,256,1,9,9725732.2
4,4,61752,100,0,0,57,64245,8,4,2018,1,0,7151,2786,863,0,7,6181908.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22725,22725,55825,84,1,0,70,12031,3,10,2000,0,0,4477,786,345,0,0,5594137.1
22726,22726,65870,88,1,0,49,23197,9,9,2015,0,1,4811,2454,755,0,7,6594705.0
22727,22727,93192,42,1,0,39,8539,10,5,2014,1,0,5595,4072,789,0,0,9321511.4
22728,22728,65797,86,1,0,89,23197,2,10,2000,1,0,5358,2513,411,0,0,6584708.2
22729,22729,82244,18,1,0,38,86728,1,9,2018,1,0,6294,1291,572,0,6,8231424.8

In [ ]:
df1

,id,squareMeters,numberOfRooms,hasYard,hasPool,floors,cityCode,cityPartRange,numPrevOwners,made,isNewBuilt,hasStormProtector,basement,attic,garage,hasStorageRoom,hasGuestRoom,price
0,0,34291,24,1,0,47,35693,2,1,2000,0,1,8,5196,369,0,3,3436795.2
1,1,95145,60,0,1,60,34773,1,4,2000,0,1,729,4496,277,0,6,9519958.0
2,2,92661,45,1,1,62,45457,4,8,2020,1,1,7473,8953,245,1,9,9276448.1
3,3,97184,99,0,0,59,15113,1,1,2000,0,1,6424,8522,256,1,9,9725732.2
4,4,61752,100,0,0,57,64245,8,4,2018,1,0,7151,2786,863,0,7,6181908.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22725,22725,55825,84,1,0,70,12031,3,10,2000,0,0,4477,786,345,0,0,5594137.1
22726,22726,65870,88,1,0,49,23197,9,9,2015,0,1,4811,2454,755,0,7,6594705.0
22727,22727,93192,42,1,0,39,8539,10,5,2014,1,0,5595,4072,789,0,0,9321511.4
22728,22728,65797,86,1,0,89,23197,2,10,2000,1,0,5358,2513,411,0,0,6584708.2
22729,22729,82244,18,1,0,38,86728,1,9,2018,1,0,6294,1291,572,0,6,8231424.8

In [ ]:
df_filtered=df[select_columns]
df_filtered

,id,squareMeters,numberOfRooms,hasYard,hasPool,floors,cityCode,cityPartRange,numPrevOwners,made,isNewBuilt,hasStormProtector,basement,attic,garage,hasStorageRoom,hasGuestRoom,price
0,0,34291,24,1,0,47,35693,2,1,2000,0,1,8,5196,369,0,3,3436795.2
1,1,95145,60,0,1,60,34773,1,4,2000,0,1,729,4496,277,0,6,9519958.0
2,2,92661,45,1,1,62,45457,4,8,2020,1,1,7473,8953,245,1,9,9276448.1
3,3,97184,99,0,0,59,15113,1,1,2000,0,1,6424,8522,256,1,9,9725732.2
4,4,61752,100,0,0,57,64245,8,4,2018,1,0,7151,2786,863,0,7,6181908.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22725,22725,55825,84,1,0,70,12031,3,10,2000,0,0,4477,786,345,0,0,5594137.1
22726,22726,65870,88,1,0,49,23197,9,9,2015,0,1,4811,2454,755,0,7,6594705.0
22727,22727,93192,42,1,0,39,8539,10,5,2014,1,0,5595,4072,789,0,0,9321511.4
22728,22728,65797,86,1,0,89,23197,2,10,2000,1,0,5358,2513,411,0,0,6584708.2
22729,22729,82244,18,1,0,38,86728,1,9,2018,1,0,6294,1291,572,0,6,8231424.8

In [ ]:
select_columns

['id',
 'squareMeters',
 'numberOfRooms',
 'hasYard',
 'hasPool',
 'floors',
 'cityCode',
 'cityPartRange',
 'numPrevOwners',
 'made',
 'isNewBuilt',
 'hasStormProtector',
 'basement',
 'attic',
 'garage',
 'hasStorageRoom',
 'hasGuestRoom',
 'price']

In [ ]:
df2 = df1.copy()

for column in df1.columns:
    q2 = df2[column].quantile(0.90)  # 90th percentile
    q1 = df2[column].quantile(0.10)
    df2 = df2[(df2[column] <= q2) & (df2[column]>=q1)]   # Remove values above the 90th percentile
df2

,id,squareMeters,numberOfRooms,hasYard,hasPool,floors,cityCode,cityPartRange,numPrevOwners,made,isNewBuilt,hasStormProtector,basement,attic,garage,hasStorageRoom,hasGuestRoom,price
2281,2281,51744,83,0,1,37,30135,5,4,1997,1,1,8778,4615,464,1,2,5181732.7
2299,2299,19572,86,0,0,28,59407,9,4,2017,0,1,8779,3283,719,1,8,1969866.7
2317,2317,49617,56,0,0,50,86885,6,5,2016,0,1,3354,6019,327,0,3,4963740.6
2319,2319,46131,38,1,0,29,83019,9,9,2005,0,1,6427,7844,249,0,7,4619824.5
2326,2326,29570,47,0,1,18,52085,4,2,2011,0,0,7584,4915,264,0,8,2962411.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20391,20391,50589,57,0,1,55,20554,5,7,2008,0,0,3538,8476,880,0,8,5061508.8
20410,20410,70898,24,0,0,35,12334,3,9,2008,1,0,8245,7767,439,1,5,7092877.8
20428,20428,32527,35,0,0,50,62591,9,4,2003,1,1,6429,4302,696,1,2,3263461.3
20452,20452,62166,36,0,1,52,16730,9,8,2009,0,1,4952,8156,216,1,4,6222231.9
20453,20453,57970,73,0,1,53,52920,7,6,2013,1,0,5751,7871,512,1,4,5811905.3

In [ ]:
# # df_filtered=df[select_columns]
# # #df=df_filtered
# #df1
# df2=df1.copy()
# columns=df1.columns
# for column in columns:
#   q2 = df2[column].quantile(0.90)
#   q1 = df2[column].quantile(0.10) #removing outliers
#   df2=df2[(df1[column] < q2) & (df2[column] > q1)]

In [ ]:
df2

,id,squareMeters,numberOfRooms,hasYard,hasPool,floors,cityCode,cityPartRange,numPrevOwners,made,isNewBuilt,hasStormProtector,basement,attic,garage,hasStorageRoom,hasGuestRoom,price
2281,2281,51744,83,0,1,37,30135,5,4,1997,1,1,8778,4615,464,1,2,5181732.7
2299,2299,19572,86,0,0,28,59407,9,4,2017,0,1,8779,3283,719,1,8,1969866.7
2317,2317,49617,56,0,0,50,86885,6,5,2016,0,1,3354,6019,327,0,3,4963740.6
2319,2319,46131,38,1,0,29,83019,9,9,2005,0,1,6427,7844,249,0,7,4619824.5
2326,2326,29570,47,0,1,18,52085,4,2,2011,0,0,7584,4915,264,0,8,2962411.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20391,20391,50589,57,0,1,55,20554,5,7,2008,0,0,3538,8476,880,0,8,5061508.8
20410,20410,70898,24,0,0,35,12334,3,9,2008,1,0,8245,7767,439,1,5,7092877.8
20428,20428,32527,35,0,0,50,62591,9,4,2003,1,1,6429,4302,696,1,2,3263461.3
20452,20452,62166,36,0,1,52,16730,9,8,2009,0,1,4952,8156,216,1,4,6222231.9
20453,20453,57970,73,0,1,53,52920,7,6,2013,1,0,5751,7871,512,1,4,5811905.3

In [ ]:
df_filtered=df_filtered[df['numberOfRooms']>=df['floors']] #removiving the building having number of floors > rooms

In [ ]:
df2

,id,squareMeters,numberOfRooms,hasYard,hasPool,floors,cityCode,cityPartRange,numPrevOwners,made,isNewBuilt,hasStormProtector,basement,attic,garage,hasStorageRoom,hasGuestRoom,price
2281,2281,51744,83,0,1,37,30135,5,4,1997,1,1,8778,4615,464,1,2,5181732.7
2299,2299,19572,86,0,0,28,59407,9,4,2017,0,1,8779,3283,719,1,8,1969866.7
2317,2317,49617,56,0,0,50,86885,6,5,2016,0,1,3354,6019,327,0,3,4963740.6
2319,2319,46131,38,1,0,29,83019,9,9,2005,0,1,6427,7844,249,0,7,4619824.5
2326,2326,29570,47,0,1,18,52085,4,2,2011,0,0,7584,4915,264,0,8,2962411.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20391,20391,50589,57,0,1,55,20554,5,7,2008,0,0,3538,8476,880,0,8,5061508.8
20410,20410,70898,24,0,0,35,12334,3,9,2008,1,0,8245,7767,439,1,5,7092877.8
20428,20428,32527,35,0,0,50,62591,9,4,2003,1,1,6429,4302,696,1,2,3263461.3
20452,20452,62166,36,0,1,52,16730,9,8,2009,0,1,4952,8156,216,1,4,6222231.9
20453,20453,57970,73,0,1,53,52920,7,6,2013,1,0,5751,7871,512,1,4,5811905.3

In [ ]:
#df_filtered=df2.drop(['ADDRESS','POSTED_BY'],axis=1)

In [ ]:
# df_filtered=df_filtered[df['numberOfRooms']<=10] #only building with less tahn 10 rooms can be house

In [ ]:
df_filtered

,id,squareMeters,numberOfRooms,hasYard,hasPool,floors,cityCode,cityPartRange,numPrevOwners,made,isNewBuilt,hasStormProtector,basement,attic,garage,hasStorageRoom,hasGuestRoom,price
1,1,95145,60,0,1,60,34773,1,4,2000,0,1,729,4496,277,0,6,9519958.0
3,3,97184,99,0,0,59,15113,1,1,2000,0,1,6424,8522,256,1,9,9725732.2
4,4,61752,100,0,0,57,64245,8,4,2018,1,0,7151,2786,863,0,7,6181908.8
5,5,30300,36,0,0,35,19069,8,4,1998,1,0,8181,1826,589,0,0,3033117.8
6,6,19341,95,1,0,37,23939,9,6,2017,0,0,7173,9233,101,0,3,1944096.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22720,22720,60886,17,0,0,5,28735,5,4,2005,0,1,4510,9402,146,0,2,6090272.5
22724,22724,13073,81,0,1,69,42152,4,6,2020,1,1,8290,8164,424,1,8,1316580.1
22725,22725,55825,84,1,0,70,12031,3,10,2000,0,0,4477,786,345,0,0,5594137.1
22726,22726,65870,88,1,0,49,23197,9,9,2015,0,1,4811,2454,755,0,7,6594705.0
22727,22727,93192,42,1,0,39,8539,10,5,2014,1,0,5595,4072,789,0,0,9321511.4

In [ ]:
df_filtered.isna().sum()

id                   0
squareMeters         0
numberOfRooms        0
hasYard              0
hasPool              0
floors               0
cityCode             0
cityPartRange        0
numPrevOwners        0
made                 0
isNewBuilt           0
hasStormProtector    0
basement             0
attic                0
garage               0
hasStorageRoom       0
hasGuestRoom         0
price                0
dtype: int64

In [ ]:
dict1={}
dict1=df_filtered.corr()
dict1

,id,squareMeters,numberOfRooms,hasYard,hasPool,floors,cityCode,cityPartRange,numPrevOwners,made,isNewBuilt,hasStormProtector,basement,attic,garage,hasStorageRoom,hasGuestRoom,price
id,1.000000,-0.000767,0.002188,-0.008792,-0.001227,-0.004520,0.012457,0.019097,-0.001281,-0.010495,0.011881,0.000996,0.000962,0.006976,0.010106,0.014791,0.006692,-0.011982
squareMeters,-0.000767,1.000000,0.041479,-0.009514,-0.011935,0.021541,0.019893,0.007793,0.000018,0.012639,0.007033,0.020734,-0.019249,-0.012428,-0.033460,0.006047,-0.008232,0.472028
numberOfRooms,0.002188,0.041479,1.000000,-0.018412,-0.017593,0.519280,-0.022960,0.005774,0.014821,-0.000776,-0.012661,-0.002907,0.033506,0.017165,0.091723,-0.002486,-0.027186,0.088252
hasYard,-0.008792,-0.009514,-0.018412,1.000000,-0.060859,-0.004657,0.001149,0.009283,0.002235,0.009166,-0.001079,0.015980,-0.014339,0.003391,-0.011309,0.018134,-0.015611,-0.003804
hasPool,-0.001227,-0.011935,-0.017593,-0.060859,1.000000,-0.024643,0.019886,-0.009622,0.001091,-0.008506,0.029425,0.012583,0.017503,-0.005964,0.006439,0.018802,-0.008618,-0.009218
floors,-0.004520,0.021541,0.519280,-0.004657,-0.024643,1.000000,-0.005214,0.010608,0.010593,-0.003514,-0.003242,-0.010502,0.016840,0.014566,0.041087,-0.005566,-0.036304,0.068432
cityCode,0.012457,0.019893,-0.022960,0.001149,0.019886,-0.005214,1.000000,0.017136,0.001357,0.005647,0.003671,-0.008701,0.000360,0.025983,0.001068,-0.005620,0.006017,0.020566
cityPartRange,0.019097,0.007793,0.005774,0.009283,-0.009622,0.010608,0.017136,1.000000,0.015096,0.012239,0.007304,0.000620,-0.003957,0.001224,0.007885,0.001935,0.016839,-0.011139
numPrevOwners,-0.001281,0.000018,0.014821,0.002235,0.001091,0.010593,0.001357,0.015096,1.000000,-0.004028,-0.001136,-0.009313,-0.011451,-0.011868,-0.006449,0.010418,0.021120,-0.014774
made,-0.010495,0.012639,-0.000776,0.009166,-0.008506,-0.003514,0.005647,0.012239,-0.004028,1.000000,-0.009163,0.010388,-0.011228,0.006218,0.013923,-0.009124,0.000189,0.024176
isNewBuilt,0.011881,0.007033,-0.012661,-0.001079,0.029425,-0.003242,0.003671,0.007304,-0.001136,-0.009163,1.000000,0.030661,0.004933,0.006417,0.002075,0.039079,0.008821,-0.003326
hasStormProtector,0.000996,0.020734,-0.002907,0.015980,0.012583,-0.010502,-0.008701,0.000620,-0.009313,0.010388,0.030661,1.000000,-0.016964,-0.006467,0.023931,0.012983,0.006553,0.025048
basement,0.000962,-0.019249,0.033506,-0.014339,0.017503,0.016840,0.000360,-0.003957,-0.011451,-0.011228,0.004933,-0.016964,1.000000,0.026239,-0.008189,-0.007436,0.011024,-0.045892
attic,0.006976,-0.012428,0.017165,0.003391,-0.005964,0.014566,0.025983,0.001224,-0.011868,0.006218,0.006417,-0.006467,0.026239,1.000000,-0.034164,-0.006092,0.023779,-0.011731
garage,0.010106,-0.033460,0.091723,-0.011309,0.006439,0.041087,0.001068,0.007885,-0.006449,0.013923,0.002075,0.023931,-0.008189,-0.034164,1.000000,0.044803,0.011158,-0.092732
hasStorageRoom,0.014791,0.006047,-0.002486,0.018134,0.018802,-0.005566,-0.005620,0.001935,0.010418,-0.009124,0.039079,0.012983,-0.007436,-0.006092,0.044803,1.000000,0.005194,-0.005388
hasGuestRoom,0.006692,-0.008232,-0.027186,-0.015611,-0.008618,-0.036304,0.006017,0.016839,0.021120,0.000189,0.008821,0.006553,0.011024,0.023779,0.011158,0.005194,1.000000,-0.016129
price,-0.011982,0.472028,0.088252,-0.003804,-0.009218,0.068432,0.020566,-0.011139,-0.014774,0.024176,-0.003326,0.025048,-0.045892,-0.011731,-0.092732,-0.005388,-0.016129,1.000000

In [ ]:
val=sorted(dict1['TARGET(PRICE_IN_LACS)'],reverse=True)
val

In [ ]:
import seaborn as sns
# sns.pairplot(df_filtered)

In [ ]:
sns.distplot(df2['price'],bins=24)

In [ ]:
dict1=df_filtered.corr()

In [ ]:
dict1['']

In [ ]:
df2['price'].skew()

In [ ]:
df2['log_price']=np.log(df2['price'])
#np.log(data['Price'])

In [ ]:
# val=sorted(dict1['price'],reverse=True)[2:9]
# val

In [ ]:
df2

In [ ]:
df2=df2.drop('price',axis=1)

In [ ]:
df2

In [ ]:
print(df2['log_price'].skew())
sns.distplot(df2['log_price'])

In [ ]:
# from numpy.lib.function_base import select #selecting the top features in colleration to price
# select_column=[]
# for column1 in dict1.keys():
#   if dict1[column1]['price'] in val:
#     select_column.append(column1)

In [ ]:
# select_column

In [ ]:
import seaborn as sns

In [ ]:
target= df2['log_price']
select_columns=list(df2.columns)
select_columns.pop()
print(target.head())
select_columns

In [ ]:
X= df2[select_columns]
y=df2['log_price']

print(X.head())

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model=LinearRegression()#heatmap
model.fit(X,target)

In [ ]:
sns.heatmap(df.corr(),cmap="coolwarm")

In [ ]:
#Train, Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=101) #dividing into traintest split

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)

In [ ]:
print(model.intercept_)

In [ ]:
coeff_df = pd.DataFrame(model.coef_,X.columns,columns=['Coefficient'])
coeff_df

In [ ]:
predictions = model.predict(X_test)
import matplotlib.pyplot as plt

In [ ]:
print(len(X_train),len(X_test),len(y_train),len(y_test))

In [ ]:
plt.scatter(model.predict(X_test),y_test) #scatter model
#plt.plot(X,model.predict(X),alpha=0.7,color='red',linewidth=4)

In [ ]:
# plt.scatter(y,m,alpha=0.3)
plt.plot(y_test,model.predict(X_test),alpha=0.7,color='red',linewidth=4)
plt.xlabel("Y Test Vaues") #regression line
plt.ylabel("Model predicted values")

In [ ]:
from sklearn import metrics

In [ ]:
print('MAE:', metrics.mean_absolute_error(y_test, predictions))
print('MSE:', metrics.mean_squared_error(y_test, predictions))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, predictions)))

In [ ]:
from sklearn.metrics import accuracy_score
X_val=model.predict(X_test)
X_val

In [ ]:
y_val=[]
for cal in y_test:
  y_val.append(cal)
y_val

In [ ]:
from sklearn.metrics import r2_score #accuracy caluculator
score = r2_score(y_val, X_val)
print("The accuracy of our model is {}%".format(round(score, 2) *100))